### ISSUE TITLE
fileprovider 

### ISSUE THREAD

**Issue by eaglewangl** [mikehardy/react-native-update-apk#12]
hello, i wonder where file provider do you place? i don't see it anywhere. so how does it works when you ues FileProvider? thanks

**Comment by mikehardy** [comment]
I see you closed the issue so I'll assume you found it in the example - excellent! - I wanted to link right to the line in the source code but then if I make changes to the file I know I'll forget to update the docs so I am relying on people to search the file a bit. I have tested a lot but the code is still fresh in many parts, please let me know if you see any other problems. Good luck

**Comment by eaglewangl** [comment]
thanks, and i meet a question today, when i use other third-party libs like 'rn-fetch-blob', it also uses file-provider , so how can i do about it?

**Comment by mikehardy** [comment]
Using this with rn-fetch-blob was the hardest part of the FileProvider thing, in my opinion. I also struggled with it.

This line is very important: https://github.com/mikehardy/react-native-update-apk/blob/master/example/android/app/src/main/AndroidManifest.xml#L40

You will need something like it in your AndroidManifest. It tells the manifest merge tool that for that Provider entry, you want to replace the one included in rn-fetch-blob.

That gives you the chance to use your own filepaths.xml file, and then it is the second important part. In that filepaths.xml you need to specify everything rn-fetch-blob needs *plus* what you need for rn-update-apk. In the example I am just using filepaths for the cache dir:

https://github.com/mikehardy/react-native-update-apk/blob/master/example/android/app/src/main/res/xml/filepaths.xml#L8

But if you are really integrating them you will want to start with the rn-fetch-blob filepaths.xml and add cache to it so your app has a filepaths with all the paths

My advice would be to play with those in the example app until it works then go back to your app. I know it works though as I am doing it successfully. Good luck!

**Comment by eaglewangl** [comment]
thank you !

**Comment by DevineDecrypter** [comment]
hi, im trying to use rn-fetch-blob with this package in the same project, i set up the files as shown in the example app, but i get this error:
`RNUpdateAPK::getVersionError - getVersionError [TypeError: Cannot read property 'CachesDirectoryPath' of undefined]`

i tried to have 2 providers in androidmanifest.xml and gave them different names as "authorities" but it didnt work, im not familiar with native code so i just tried to try random things until i get it working but it didnt work out.

this is the provider i have in androidmanifest.xml:
```
<provider
        android:name="androidx.core.content.FileProvider"
        android:authorities="com.lorem.provider"
        android:exported="false"
        android:grantUriPermissions="true">
        <meta-data
          android:name="android.support.FILE_PROVIDER_PATHS"
          android:resource="@xml/filepaths" />
      </provider>
```
the filepaths is like this:

```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <cache-path name="cache" path="/" />
</paths>
```

a long time is past but if you remember how you solved your problem i would really appreciate your help on this matter, thank you.

**Comment by mikehardy** [comment]
Everything about how this works is in the example app.

**Comment by DevineDecrypter** [comment]
I had to manually install react-native-fs, and link it.
