### ISSUE TITLE
APP startup crashes

### ISSUE THREAD

**Issue by lanjinli** [mikehardy/react-native-update-apk#17]
Android crashes by doing the following

![4](https://user-images.githubusercontent.com/42225063/62264584-12ab1d00-b453-11e9-8fd6-00215022a76f.png)
![5](https://user-images.githubusercontent.com/42225063/62264585-12ab1d00-b453-11e9-9e59-1139489acf40.png)
![0](https://user-images.githubusercontent.com/42225063/62264587-1343b380-b453-11e9-8913-1d5f98a3136f.png)
![1](https://user-images.githubusercontent.com/42225063/62264588-1343b380-b453-11e9-9921-82fad45e8fcb.png)
![2](https://user-images.githubusercontent.com/42225063/62264589-13dc4a00-b453-11e9-8f5c-2a0916c1d981.png)
![3](https://user-images.githubusercontent.com/42225063/62264590-13dc4a00-b453-11e9-9989-00091d26937f.png)

Open the collapse

**Comment by mikehardy** [comment]
Show me a stack trace from logcat or I can't tell why. Try the example app also, it works fine for me
