### ISSUE TITLE
This is problem in RN0.60.5, when I run-android

### ISSUE THREAD

**Issue by garraly** [mikehardy/react-native-update-apk#19]
![WX20190905-111830](https://user-images.githubusercontent.com/36126068/64309549-6919f700-cfcf-11e9-8aad-252d25edb7d9.png)
---
ERROR: Unable to resolve dependency for ':rn-update-apk@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0.
Show Details
Affected Modules: rn-update-apk
ERROR: Unable to resolve dependency for ':rn-update-apk@debug/compileClasspath': Could not resolve androidx.appcompat:appcompat:{strictly 1.0.0}.
Show Details
Affected Modules: rn-update-apk
ERROR: Unable to resolve dependency for ':rn-update-apk@debug/compileClasspath': Could not resolve androidx.core:core:{strictly 1.0.0}.
Show Details
Affected Modules: rn-update-apk
ERROR: Unable to resolve dependency for ':rn-update-apk@debug/compileClasspath': Could not resolve androidx.vectordrawable:vectordrawable:{strictly 1.0.0}.
Show Details
Affected Modules: rn-update-apk
ERROR: Unable to resolve dependency for ':rn-update-apk@debug/compileClasspath': Could not resolve androidx.appcompat:appcompat:1.0.2.
Show Details
Affected Modules: rn-update-apk
ERROR: Unable to resolve dependency for ':rn-update-apk@debug/compileClasspath': Could not resolve androidx.core:core:1.0.1.
Show Details
Affected Modules: rn-update-apk
ERROR: Unable to resolve dependency for ':rn-update-apk@debug/compileClasspath': Could not resolve androidx.vectordrawable:vectordrawable:1.0.1.
Show Details
Affected Modules: rn-update-apk
ERROR: Unable to resolve dependency for ':rn-update-apk@debug/compileClasspath': Could not resolve androidx.core:core:1.0.0.
Show Details
Affected Modules: rn-update-apk
ERROR: Unable to resolve dependency for ':rn-update-apk@debug/compileClasspath': Could not resolve androidx.vectordrawable:vectordrawable:1.0.0.
Show Details
Affected Modules: rn-update-apk
---
I guess RN0.60+ uses androidx package, not android

**Comment by mikehardy** [comment]
https://facebook.github.io/react-native/blog/2019/07/03/version-60#androidx-support

**Comment by mikehardy** [comment]
https://github.com/mikehardy/react-native-update-apk/blob/master/example/android/build.gradle#L9
