### ISSUE TITLE
Getting Network error while implementing in my code

### ISSUE THREAD

**Issue by ashishBharadwaj** [mikehardy/react-native-update-apk#26]
@mikehardy : Please help me in fixing this
This is how I am passing data to apkVersionURL
![image](https://user-images.githubusercontent.com/8766201/76397776-b2456c00-63a1-11ea-939e-363dec53b49f.png)

**Comment by mikehardy** [comment]
I will not troubleshoot project-specific code, there are so many ways it can go wrong. I will certainly not do so with images of errors, programming is a text-based activity, post actual code

Tell me how it worked with the example, if you can reproduce an error with the example, I can fix it. I did my best to make the example complete and check that it runs out of the box

**Comment by ashishBharadwaj** [comment]
@mikehardy : I am getting the same error with the example as well

**Comment by mikehardy** [comment]
Ok, so the example uses https://github.com/mikehardy/react-native-update-apk/blob/10db4e01be23b00262e1d4a6ef2e19e909f1c2ef/example/App.js#L38

which is https://raw.githubusercontent.com/mikehardy/react-native-update-apk/master/example/test-version.json

It works for me - if you can't get to that from your device, you have a major network issue. Check `adb logcat`, try well-known URLs directly etc.

Maybe there is a TLS issue similar to #11 / #13 

What you're trying to do - perform network requests and directly update application code is pretty low-level stuff. You are going to have to be VERY resourceful and debug this yourself, as I can't reproduce it.

**Comment by IshaTyagi** [comment]
@mikehardy : Is there a way to directly pass the JSON object rather than the url?

**Comment by mikehardy** [comment]
@IshaTyagi No there is not, but I understand it might be nice to have "out-of-band" version information from somewhere else (some database or something, anything) so if that's something you need, and you make a backwards-compatible PR for it, I'd be happy to merge it
