### ISSUE TITLE
ios getVersionError

### ISSUE THREAD

**Issue by jiapeng007** [mikehardy/react-native-update-apk#29]
![image](https://user-images.githubusercontent.com/32921739/82168447-5e02bf00-98f1-11ea-8177-36a404a5b62a.png)

but my app store address is like "https://itunes.apple.com/cn/app/"，so getVersionError.

**Comment by mikehardy** [comment]
Hi there! Propose a PR that adds an optional (has a default value of the current URL) parameter for that API so you can override it, and I'll merge it in

**Comment by mikehardy** [comment]
(and worth noting - while you develop the PR and until it's merged you can use the excellent patch-package module to use your change in your project easily, so you are not blocked)

**Comment by jiapeng007** [comment]
![image](https://user-images.githubusercontent.com/32921739/82172948-5695e280-98fe-11ea-8362-e786a68046a3.png)

I have fixed it like this. please review.

**Comment by mikehardy** [comment]
Ah that's even cleaner - that should work for all locations I think - have you tested a CN and a US app? If you propose this as a PR and confirm you have tested I can merge it in

**Comment by mikehardy** [comment]
Fixed in 4.4.0 thanks @jiapeng007
