### ISSUE TITLE
node_modules\rn-update-apk\android\src\main\java\net\mikehardy\rnupdateapk\RNUpdateAPK.java:11: error: package android.support.v4.content does not exist import android.support.v4.content.FileProvider;

### ISSUE THREAD

**Issue by saifulhq** [mikehardy/react-native-update-apk#31]
I got this error when running android > gradlew assembleRelease
is there any config that i missing?

**Comment by mikehardy** [comment]
Ironically, since I maintain jetifier, I still haven't converted this package to be AndroidX native.
Just didn't seem important since jetifier exists.

Anyway, that's what you're missing -> https://github.com/mikehardy/jetifier#to-jetify--convert-node_modules-dependencies-to-androidx

**Comment by saifulhq** [comment]
thank's this working
