### ISSUE TITLE
Error android when update

### ISSUE THREAD

**Issue by studiozocaro** [mikehardy/react-native-update-apk#43]
after download i receive this error:
attempt to invoke virtual method 'android.content.res.xmlresourceparser android.content.pm.providerinfo.loadxmlmetadata(android.content.pm.packagemanager,java.lang.string)' on a null object reference

[https://api.svogly.com:3001/err.jpeg](url)

**Comment by mikehardy** [comment]
Hi there!

What version of react-native-update-apk?
Using what code *exactly*?

What is the *text* of the actual error message from your logs? Do not post error images, I will offer no help for those.

In general, follow these guidelines when opening an issue on any project: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by studiozocaro** [comment]
Post error images

[](url![image](https://user-images.githubusercontent.com/58362072/122824349-cf752400-d2e0-11eb-8259-b136bd7827f9.png)[](url)

**Comment by studiozocaro** [comment]
Error after download apk
huawei android 11

**Comment by mikehardy** [comment]
> Hi there!
> 
> What version of react-native-update-apk?
> Using what code _exactly_?
> 
> What is the _text_ of the actual error message from your logs? Do not post error images, I will offer no help for those.
> 
> In general, follow these guidelines when opening an issue on any project: https://stackoverflow.com/help/minimal-reproducible-example

You followed exactly none of my instructions.
