### ISSUE TITLE
How to access the whatNew property?

### ISSUE THREAD

**Issue by brett-fz** [mikehardy/react-native-update-apk#47]
Hi guys,

I'm just wondering how do I access the whatsNew property so I can display it to my user in react native?

Cheers.

**Comment by mikehardy** [comment]
Hi there -

Looks like it will come through as the second argument to whatever function you send in for options.needUpdateApp

https://github.com/mikehardy/react-native-update-apk/blob/594096977684c8c26318aa1920edc742e65d68dc/index.js#L74-L80
