### ISSUE TITLE
supperts typescript? 

### ISSUE THREAD

**Issue by Johnny159** [mikehardy/react-native-update-apk#51]
Supperts typescript? 

Thanks.

**Comment by mikehardy** [comment]
A cursory glance at the library shows no types, right? So...no. But I write entirely in typescript these days and use it just fine.
I just have a types entry that says "ignore the types here" and use it untyped. :shrug: . It's a tiny library, never seemed important to do.

If you propose a PR that types the library with an index.d.ts file I will *happily* merge it, I do love types, just haven't had the time

Cheers

**Comment by ScreamZ** [comment]
https://github.com/mikehardy/react-native-update-apk/pull/80
