### ISSUE TITLE
installApk exception with authority name com.qls & Couldn't find meta-data for provider with authority com.qls

### ISSUE THREAD

**Issue by trunglemobiledev** [mikehardy/react-native-update-apk#70]
i have some problem when android build crashes app after successful download,
i use RN ver 0.61.4
![image](https://user-images.githubusercontent.com/54437116/199174914-68ac780d-4ba6-4302-9260-657ef21cc765.png)
![image](https://user-images.githubusercontent.com/54437116/199174970-d98ac87f-88b8-463f-b4d1-0a92cb868254.png)
Thanks

**Comment by mikehardy** [comment]
You have reported a crash but not included result of `adb logcat` so no help may be provided
Additionally, react-native 0.61 is *far* far far too old to be the base of any work. React-native 0.64 does not even compile with Xcode current versions anymore, 0.65 is the oldest I would even consider trying at this point.

If you want help, please try again *posting text using markdown formatting* and including all important information

https://stackoverflow.com/help/how-to-ask
