### ISSUE TITLE
I am getting error while running example on click of CHECK SERVER FOR UPDATE

### ISSUE THREAD

**Issue by Kailash23** [mikehardy/react-native-update-apk#72]
Error:
Alert title - There was an error 
Alert message -Cannot read property "versionCode" of null

Using RN 0.70.6

Any idea what went wrong ?

**Comment by mikehardy** [comment]
> Any idea what went wrong 

Nope, sorry. Not really a full set of steps to reproduce https://stackoverflow.com/help/how-to-ask so I can't help.

**Comment by Kailash23** [comment]
Let me try to replicate this in a fresh project 0.70.6.
Then I will get back to you.

**Comment by Kailash23** [comment]
Lib is working fine. It was configuration issue.
